### PR TITLE
Fix travis

### LINKED ISSUE #47: Travis seems to fail

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #47

### CODE REVIEW

File: owncloud/appManagement.js [hunk 1]
```diff
@@ -53,9 +53,9 @@ apps.prototype.getApps = function() {
                     return;
                 }
 
-                if ((!(data in parser.xml2js(apps[0].body).ocs)) || (!(data in parser.xml2js(apps[1].body).ocs))) {
-                    reject(parser.xml2js(apps[0].body).ocs);
-                }
+                // if ((!(data in parser.xml2js(apps[0].body).ocs)) || (!(data in parser.xml2js(apps[1].body).ocs))) {
```
Comment (PVince81) [inline owncloud/appManagement.js]: why?

Comment (DeepDiver1975) [reply owncloud/appManagement.js]: data is undefined - no idea where data is supposed to come from.

deeper insights are welcome ....

Comment (PVince81) [reply owncloud/appManagement.js]: maybe it's supposed to be double quoted: `"data"` as the block seems to try and detect wheter "ocs.data" exists.

a simpler way to write this would be `if (parser.xml2js(apps[0].body).ocs.data)`

Comment (PVince81) [reply owncloud/appManagement.js]: probably not double quoted though... it does seem to be the equivalent of PHP's `isset`.

I suggest rewriting to the latter form
